static const char black[]       = "#222526";
static const char gray2[]       = "#282b2c"; // unfocused window border
static const char gray3[]       = "#5d6061";
static const char gray4[]       = "#282b2c";
static const char blue[]        = "#458588";  // focused window border
static const char green[]       = "#98971a";
static const char red[]         = "#cc241d";
static const char orange[]      = "#d65d0e";
static const char yellow[]      = "#d79921";
static const char pink[]        = "#cc7f94";
static const char col_borderbar[]  = "#222526"; // inner border
